### ISSUE TITLE
Enclose `command.cpp` math macros with #undefs

### ISSUE THREAD

**Issue by no-lex** [project-imprimis/imprimis#129]
https://github.com/project-imprimis/imprimis/blob/88021113617ebfc745ca1896a819aac323bfef7b/src/engine/interface/command.cpp#L6303-L6337

https://github.com/project-imprimis/imprimis/blob/88021113617ebfc745ca1896a819aac323bfef7b/src/engine/interface/command.cpp#L6429-L6456

https://github.com/project-imprimis/imprimis/blob/88021113617ebfc745ca1896a819aac323bfef7b/src/engine/interface/command.cpp#L6506-L6523

https://github.com/project-imprimis/imprimis/blob/88021113617ebfc745ca1896a819aac323bfef7b/src/engine/interface/command.cpp#L6551-L6570

These series of macros are only used for a short while, but do not get `#undef`-d such that they pollute the global namespace; to resolve this, placing `#undef` directives following their last actual use will prevent them from being available globally.

**Comment by nonoesimposible** [comment]
Hello, I would be interested in working on this. :slightly_smiling_face:

**Comment by no-lex** [comment]
Great, you're been assigned to it.
