### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by PavanLuca** [project-imprimis/imprimis#81]
By the way, as you can see 👇, the icon is missing, too. I can anyway launch the game despite it looks a text file 😄.
![immagine](https://github.com/project-imprimis/imprimis/assets/123581658/d085c54b-3149-470b-b25e-67a6ace35628)
![Schermata del 2024-07-11 16-54-08](https://github.com/project-imprimis/imprimis/assets/123581658/fb82dd36-2065-496d-9017-bedb8806eeda)
```
Setting home folder: /snap/imprimis-game/219
init: sdl
(null) found
init: net
init: cubescript
init: game
init: video
Error: Missing GL version
init: GLEW 2.2.0
failed to create OpenGL context: Could not create GL context: GLXBadFBConfig
```
 - OS: Zorin OS Core 17.1
 - Commit hash (I don't know neither where it is nor what it is)

**Comment by no-lex** [comment]
The OpenGL subsystem on the base operating system is what is used for Snap installs of the game. What is the OpenGL context on your machine (`glxinfo -B`)?

**Comment by PavanLuca** [comment]
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa (0x1002)
    Device: AMD RS880 (DRM 2.50.0 / 6.5.0-26-generic, LLVM 15.0.7) (0x9712)
    Version: 38674.1.8
    Accelerated: yes
    Video memory: 256MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 255 MB, largest block: 255 MB
    VBO free aux. memory - total: 509 MB, largest block: 509 MB
    Texture free memory - total: 255 MB, largest block: 255 MB
    Texture free aux. memory - total: 509 MB, largest block: 509 MB
    Renderbuffer free memory - total: 255 MB, largest block: 255 MB
    Renderbuffer free aux. memory - total: 509 MB, largest block: 509 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 256 MB
    Total available memory: 765 MB
    Currently available dedicated video memory: 255 MB
OpenGL vendor string: Mesa
OpenGL renderer string: AMD RS880 (DRM 2.50.0 / 6.5.0-26-generic, LLVM 15.0.7)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 24.2~git2407100600.ae3e0a~oibaf~j (git-ae3e0ae 2024-07-10 jammy-oibaf-ppa)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 24.2~git2407100600.ae3e0a~oibaf~j (git-ae3e0ae 2024-07-10 jammy-oibaf-ppa)
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 24.2~git2407100600.ae3e0a~oibaf~j (git-ae3e0ae 2024-07-10 jammy-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by no-lex** [comment]
Thanks for getting that information. Unfortunately, your GPU does not support OpenGL 4.0, which is the minimum supported OpenGL standard for Imprimis. Additionally, with only 40 shading units, I don't believe it would be able to play the game at a usable frame rate. I would recommend at least a Radeon 8670/R7 250 GPU for usable performance running the game.

Let me know if there's anything else I can do to help.

**Comment by PavanLuca** [comment]
At first I installed Imprimis because I thought it would work like Tesseract since they are very similar. Wouldn't it be possible to make Imprimis work with earlier OpenGL as well? I generally see that games provide a minimum of choice, be it graphics options, shaders, graphics drivers or whatever so I was thinking the same for OpenGL. Personally so far I've been able to run other rather heavy games (such as Xonotic, Red Eclipse, Alien Arena, Nexuiz and Minetest) despite my limited technical specs, I simply turned off all the options that put a lot of load on my laptop thus making them run. They have limited special effects and aren't necessarily beautiful but at least playable. My priority is that games are playable and funny, not beautiful or graphically perfect.

**Comment by no-lex** [comment]
It is probably possible with enough modification of the source code to make Imprimis run on such an old device. The rendering code of Imprimis differs significantly from Tesseract, with many of the old rendering pathways removed or modified in order to facilitate moving to OpenGL ES 3 platforms in the future. I do not have the time, hardware, or will to support hardware of that age, and have no intentions of reintroducing and supporting devices from that era. I hope you understand that I have limited resources and cannot support every use case.
