### ISSUE TITLE
Visibility suffers on lowest settings.

### ISSUE THREAD

**Issue by azkoon** [project-imprimis/imprimis#9]
For example here it's impossible to guess the geometry of the wall without any depth information, e.g. as provided by ambient occlusion.
![](https://cdn.discordapp.com/attachments/679461611265851423/795375155593084928/2021-01-03_13.14.04.png)
Solution might be to enforce certain settings as the lowest.

**Comment by no-lex** [comment]
The better solution here is to require GI, I think:

GI only:
![gi](https://user-images.githubusercontent.com/23445929/103491063-7ecf4480-4dee-11eb-81fa-52f15c96ecd3.png)

AO only:
![ao](https://user-images.githubusercontent.com/23445929/103491064-7ecf4480-4dee-11eb-9094-a76b7a2f1d40.png)

Neither:
![none](https://user-images.githubusercontent.com/23445929/103491065-7f67db00-4dee-11eb-8b05-31d30182b3b9.png)

**Comment by azkoon** [comment]
After testing in a couple places GI consistently provides much better results, and seems to perform better as well.
